version: '3.7'
services:
  bot:
    depends_on:
      - redis
    build:
      context: ./services/bot/
    volumes:
      - type: bind
        source: $PWD/services/bot/
        target: /app/
      - type: volume
        source: db
        target: /db/
    ports:
      - 3001:3001
    env_file:
      - .env
    restart: always
  api-server:
    build:
      context: ./services/api-server
    volumes:
      - type: bind
        source: $PWD/services/api-server/
        target: /home/node/app/
      - type: volume
        source: db
        target: /db/
    ports:
      - 3000:3000
    env_file:
      - .env
    command: node src/index.js
    restart: always
  redis:
    image: redis:5-alpine
    restart: always
  web:
    image: nginx:alpine
    volumes:
      - type: bind
        source: $PWD/services/web/dist/
        target: /usr/share/nginx/html/
        read_only: true
    ports:
      - 80:80
    restart: always
volumes:
  db:
